server:
  port: 8771

eureka:
  instance:
    hostname: www.zzy.com
    # 默认多少秒向服务器发送心跳
    lease-renewal-interval-in-seconds: 30
    # 默认服务器多少秒接收不到客户端心跳，就在eureka服务器注册表中删除该客户端实例
    lease-expiration-duration-in-seconds: 90
  client:
    service-url:
      # eureka-server的地址,多个以逗号分隔
      defalutZone: http://www.zzy.com:8761/eureka/
    # 健康自检周期，默认30秒，单位秒
    initial-instance-info-replication-interval-seconds: 10
    # 客户端默认30秒去服务端抓取注册信息
    registry-fetch-interval-seconds: 30

